---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-viewer
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: ken
roleRef:
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io/v1