---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%    
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: veter9/python36
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10    
        volumeMounts:
        - name: app
          mountPath: /app
        resources:  
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"  
      initContainers:
      - name: init-web
        image: busybox:latest
        volumeMounts:
        - name: app
          mountPath: /app
        command: ['sh', '-c', 'wget -O- --no-check-certificate https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh'] 
      volumes:
      - name: app
        emptyDir: {}    