apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: veter9/python36
    volumeMounts:
    - name: app
      mountPath: /app
    resources:  
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"  
  initContainers:
  - name: init-web
    image: busybox:latest
    volumeMounts:
    - name: app
      mountPath: /app
    command: ['sh', '-c', 'wget -O- --no-check-certificate https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh'] 
  volumes:
  - name: app
    emptyDir: {}
    