---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 namespace: prometheus
 name: pod-viewer
rules:
  - apiGroups: ["*"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]  
  