---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-role-binding
roleRef:
  kind: ClusterRole
  name: pod-viewer
  apiGroup: rbac.authorization.k8s.io  
subjects:
- kind: ServiceAccount
  name: prometheus
  apiGroup: rbac.authorization.k8s.io